export const ACTIVE_COMPONENT = 'ACTIVE_COMPONENT';
export const ACTIVE_ITEM = 'ACTIVE_ITEM';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const OPEN_COMPONENT_DRAWER = 'OPEN_COMPONENT_DRAWER';

export const ADD_ARTICLE = 'ADD_ARTICLE';
export const GET_ARTICLE = 'GET_ARTICLE';

export const ADD_EDITORIAL = 'ADD_EDITORIAL';
export const GET_EDITORIAL = 'GET_EDITORIAL';

export const SIGNUP = 'SIGNUP';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGGEDIN = 'LOGGEDIN';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const ADD_SUBJECT = 'ADD_SUBJECT';
export const GET_SUBJECT = 'GET_SUBJECT';
export const DELETE_SUBJECT='DELETE_SUBJECT';

export const ADD_MEDIUM = 'ADD_MEDIUM';
export const GET_MEDIUM = 'GET_MEDIUM';
export const DELETE_MEDIUM='DELETE_MEDIUM';

export const ADD_LEVEL = 'ADD_LEVEL';
export const GET_LEVEL = 'GET_LEVEL';
export const DELETE_LEVEL='DELETE_LEVEL';

export const ADD_LANGUAGE = 'ADD_LANGUAGE';
export const GET_LANGUAGE = 'GET_LANGUAGE';
export const DELETE_LANGUAGE = 'DELETE_LANGUAGE';

export const ADD_COURSE = 'ADD_COURSE';
export const GET_COURSE = 'GET_COURSE';

export const ADD_LIVECLASS = 'ADD_LIVECLASS';
export const GET_LIVECLASS = 'GET_LIVECLASS';

export const ADD_UPLOADCONTENT = 'ADD_UPLOADCONTENT';
export const GET_UPLOADCONTENT = 'GET_UPLOADCONTENT';

export const ADD_IMPORTANT_ISSUES = 'ADD_IMPORTANT_ISSUES';
export const GET_IMPORTANT_ISSUES = 'GET_IMPORTANT_ISSUES';

export const ADD_WEEKLY_NEWS = 'ADD_WEEKLY_NEWS';
export const GET_WEEKLY_NEWS = 'GET_WEEKLY_NEWS';

export const ADD_REGISTER_USER = 'ADD_REGISTER_USER';
export const GET_REGISTER_USER = 'GET_REGISTER_USER';
export const DELETE_REGISTER_USER = 'DELETE_REGISTER_USER';
export const GET_DELETE_USER='GET_DELETE_USER';
export const RESTORE_USER='RESTORE_USER';

export const GET_LEAD = 'GET_LEAD';
export const ADD_LEAD = 'ADD_LEAD';

export const ADD_CONTACT = 'ADD_CONTACT';

export const ADD_ADDRESS = 'ADD_ADDRESS';

export const ADD_LEAD_FORM_USER = 'ADD_LEAD_FORM_USER';

export const ADD_REGISTER_EMPLOYEE = 'ADD_REGISTER_EMPLOYEE';
export const GET_EMPLOYEE='GET_EMPLOYEE';
export const GET_DELETE_EMPLOYEE='GET_DELETE_EMPLOYEE';

export const ADD_APPOINTMENT='ADD_APPOINTMENT';

export const ADD_ASSIGN_LEAD='ADD_ASSIGN_LEAD';

export const GET_LEAD_BY_LEAD_CODE_REQUEST ='GET_LEAD_BY_LEAD_CODE_REQUEST ';
export const GET_LEAD_BY_LEAD_CODE_SUCCESS='GET_LEAD_BY_LEAD_CODE_SUCCESS ';
export const GET_LEAD_BY_LEAD_CODE_FAILURE ='GET_LEAD_BY_LEAD_CODE_FAILURE ';

export const UPDATE_LEAD_SUCCESS='UPDATE_LEAD_SUCCESS';
export const UPDATE_LEAD_FAILURE='UPDATE_LEAD_FAILURE';
export const UPDATE_LEAD_REQUEST='UPDATE_LEAD_REQUEST';

export const DELETE_LEAD_REQUEST = 'DELETE_LEAD_REQUEST';
export const DELETE_LEAD_SUCCESS = 'DELETE_LEAD_SUCCESS';
export const DELETE_LEAD_FAILURE = 'DELETE_LEAD_FAILURE';

export const RESTORE_LEAD_REQUEST = 'RESTORE_LEAD_REQUEST';
export const RESTORE_LEAD_SUCCESS = 'RESTORE_LEAD_SUCCESS';
export const RESTORE_LEAD_FAILURE = 'RESTORE_LEAD_FAILURE';

export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const RESTORE_EMPLOYEE = 'RESTORE_EMPLOYEE';
